{config, pkgs, ...}:
{
  home.packages = with pkgs; [
     appimage-run
     arandr
     betterlockscreen
     bitwarden
     brave
     btop
     catppuccin-cursors
     catppuccin-gtk 
     catppuccin-kde
     catppuccin-papirus-folders 
     dracula-icon-theme
     dracula-theme
     feh
     firefox
     flameshot
     font-manager 
     galculator
     geany
     gh
     gimp-with-plugins
     glances
     google-authenticator
     google-chrome
     guake
     hplipWithPlugin
     htop
     keepassxc
     lazygit
     lxappearance
     meld
     networkmanagerapplet
     nitrogen
     oh-my-zsh
     pcmanfm
     picom
     polkit_gnome
     polybar
     rofi
     signal-desktop
     telegram-desktop
     timeshift
     tor
     tor-browser-bundle-bin
     torsocks
     udiskie
     udisks
     veracrypt
     viewnior
     vlc
     volumeicon
     yubikey-agent
     yubikey-agent
     yubikey-manager
     yubikey-manager
     yubioath-flutter
   ];
}
